### ISSUE TITLE
Installation doesnt work

### ISSUE THREAD

**Issue by thorstenwagner** [mardiros/TOTP_Clipboard-guillaume.gauvr.it#1]
Hi,

when I try to apply the command
`gsettings get org.gnome.shell enabled-extensions ['alternate-tab@gnome-shell-extensions.gcampax.github.com', 'nohotcorner@azuri.free.fr'}`

I get

> Aufruf:
>   gsettings [--schemadir SCHEMADIR] get SCHEMA[:PFAD] SCHLÜSSEL
> 
> Den Wert von SCHLÜSSEL ermitteln
> 
> Argumente:
>   SCHEMADIR Ein Ordner zum Suchen nach zusätzlichen Schemas
>   SCHEMA      Die Kennung des Schemas
>   SCHLÜSSEL   Der Name des Schlüssels
>   SCHLÜSSEL Der Schlüssel innerhalb des Schemas

It seems there is an error in your installation manual?

I'm using archlinux with latest updates.

Cheers,
Thorsten

**Comment by mardiros** [comment]
Hi Thorsten,

I also use Archlinux, updated, and add support for Gnome Shell 3.20.

`gsettings get org.gnome.shell enabled-extensions` works just fine.

```
guillaume:~/workspace/git/TOTP_Clipboard-guillaume.gauvr.it [master] % gsettings get org.gnome.shell enabled-extensions 
['TOTP_Clipboard@guillaume.gauvr.it', 'nohotcorner@azuri.free.fr', 'alternate-tab@gnome-shell-extensions.gcampax.github.com', 'suspend-button@laserb', 'drop-down-terminal@gs-extensions.zzrough.org', 'text_translator@awamper.gmail.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'remove-dropdown-arrows@mpdeimos.com']

```

If you have problem with the command line,
Try to edit this configuration with the `dconf-editor` ?

**Comment by thorstenwagner** [comment]
After the lastest update it works! :-) Thanks!
